### ISSUE TITLE
Audio live stream error

### ISSUE THREAD

**Issue by gurupriyan-ks** [kaltura/kaltura-player-android#72]
I'm working on a live radio app, and everything is working fine but, I've got two radio stations out of which one is not working, I keep getting the following error, please check this,

2020-04-02 20:20:32.912 29246-4191/com.mobomo.radio V/ExoAnalyticsAggregator: connectionReleased = https://cdnapisec.kaltura.com/p/2610081/sp/2610081/playManifest/entryId/0_phc00jkg/deliveryProfileId/672/protocol/https/format/applehttp/a.m3u8?clientTag=playkit%2Fandroid-4.5.0&playSessionId=a193a4ea-daa0-4b3a-b54d-3c5d67a2d4bb%3A3cadb04f-e3fc-4dca-8b15-a830eba02a24&referrer=YXBwOi8vY29tLm1vYm9tby5yYWRpbw%3D%3D
2020-04-02 20:20:32.920 29246-29246/com.mobomo.radio V/ExoAnalyticsAggregator: onLoadCompleted trackType = -1, mediaLoadData.dataType 4, 8343 https://mbnvaudioingest-i.akamaihd.net/hls/live/1004562/MBNV_SAWA_LEVANT/merge.m3u8
2020-04-02 20:20:32.922 29246-4209/com.mobomo.radio V/ExoAnalyticsAggregator: callStart = https://mbnvaudioingest-i.akamaihd.net/hls/live/1004562/MBNV_SAWA_LEVANT/master.m3u8
2020-04-02 20:20:32.925 29246-4209/com.mobomo.radio V/ExoAnalyticsAggregator: connectionAcquired = https://mbnvaudioingest-i.akamaihd.net/hls/live/1004562/MBNV_SAWA_LEVANT/master.m3u8
2020-04-02 20:20:34.308 29246-4009/com.mobomo.radio V/ExoAnalyticsAggregator: secureConnectStart
2020-04-02 20:20:35.784 29246-4209/com.mobomo.radio V/ExoAnalyticsAggregator: connectionReleased = https://mbnvaudioingest-i.akamaihd.net/hls/live/1004562/MBNV_SAWA_LEVANT/master.m3u8
2020-04-02 20:20:35.784 29246-4209/com.mobomo.radio V/ExoAnalyticsAggregator: connectionReleased SEND EVENT URL = https://mbnvaudioingest-i.akamaihd.net/hls/live/1004562/MBNV_SAWA_LEVANT/master.m3u8
    dnsDurationMs = 0
    tlsDurationMs = 0
    connectDurationMs = 2
2020-04-02 20:20:35.791 29246-31486/com.mobomo.radio E/ExoPlayerImplInternal: Source error.
    com.kaltura.android.exoplayer2.ParserException: Loaded playlist has unexpected type.
        at com.kaltura.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:528)
        at com.kaltura.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:443)
        at com.kaltura.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:463)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-04-02 20:20:35.792 29246-29246/com.mobomo.radio D/ExoPlayerWrapper: onPlayerError error type => 0
2020-04-02 20:20:35.792 29246-29246/com.mobomo.radio E/ExoPlayerWrapper: com.kaltura.android.exoplayer2.ParserException: Loaded playlist has unexpected type.
2020-04-02 20:20:35.792 29246-29246/com.mobomo.radio E/ExoPlayerWrapper: Error-Event sent, type = 0
2020-04-02 20:20:35.793 29246-29246/com.mobomo.radio V/ExoPlayerWrapper: getDuration
2020-04-02 20:20:35.793 29246-29246/com.mobomo.radio D/ExoPlayerWrapper: onTimelineChanged reason = 0 duration = -9223372036854775807
2020-04-02 20:20:35.793 29246-29246/com.mobomo.radio D/ExoPlayerWrapper: Event sent: LOADED_METADATA
2020-04-02 20:20:35.793 29246-29246/com.mobomo.radio V/ExoPlayerWrapper: getDuration
2020-04-02 20:20:35.793 29246-29246/com.mobomo.radio D/ExoPlayerWrapper: onPlayerStateChanged. IDLE. playWhenReady => true
2020-04-02 20:20:35.845 29246-29246/com.mobomo.radio E/DataHandler: Playback ERROR. errorCode : 7000

**Comment by kaltura-hooks** [comment]
Hi @gurupriyan-ks,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,
